know_users/users/models.py
from flask import current_app, request
from flask.ext.login import UserMixin

# No database here, for now we use a simple (no-persistent) dict

all_users = {}

class User(UserMixin):
    def __init__(self, username, email, password):
        self.id = username
        self.email = email
        self.password = password

    @classmethod
    def get(cls, user_id):
        """
        Retrieve a user from his login name.

        :param user_id: unicode ID of a user, as store by Flask-Login in session.
        :return: the corresponding user object, or `None` if user_id is not valid
        """
        return all_users.get(user_id)

    @classmethod
    def add(cls, user):
        assert isinstance(user, User)
        user_id = user.get_id()
        assert(user_id not in all_users)
        all_users[user_id] = user

        if request:
            current_app.logger.info("User %r added", user_id)

    def is_valid_password(self, password):
        # TODO encrypt password when persisted
        return password and self.password == password

User.add(User('admin','admin@example.com', 'default'))

know_users/users/forms.py
from flask import current_app
from flask.ext.wtf import Form
from wtforms import validators,  ValidationError, BooleanField, StringField, PasswordField
from .models import User



class LoginForm(Form):
    username = StringField('Username', [validators.DataRequired()])
    password = PasswordField('Password', [validators.DataRequired()])

    # WTForms supports "inline" validators
    # of the form `validate_[fieldname]`.
    # This validator will run after all the
    # other validators have passed.
    def validate_password(form, field):
        user = User.get(form.username.data)
        if user is None:
            raise ValidationError("Unknown user")
        if not user.is_valid_password(form.password.data):
            raise ValidationError("Invalid password")

        # Make the current user available
        # to calling code.
        form.user = user

class RegistrationForm(Form):
    username = StringField('Username', [validators.Length(min=4, max=25)])
    #username = StringField('Username', [validators.DataRequired()])
    email = StringField('Email Address', [validators.Email()])
    #email = StringField('Email Address', [validators.DataRequired()])
    password = PasswordField('New Password', [
        validators.DataRequired(message='Your password protects you against identity theft'),
        validators.EqualTo('confirm', message='Passwords must match')])
    #password = PasswordField('New Password', [validators.DataRequired()])
    confirm = PasswordField('Repeat Password')
    accept_tos = BooleanField('I accept the TOS',
                              [validators.AnyOf((True,),
                                    message="You cannot register unless you accept the TOS")])

    def validate_username(self, field):
        user = User.get(self.username.data)
        if user is not None:
            raise ValidationError("This user name is already used")
        return True

know_users/__init__.py
from flask import Flask
from auth import login_manager
from users.views import bp as bp_users

app = Flask(__name__)


app.config.from_object('config')
app.config.from_envvar('PLAYGROUND_SETTINGS', silent=True)

@app.context_processor
def provide_constants():
    return {"constants": {"APP_NAME": "KnowUsers"}}

#db.init_app(app)

login_manager.init_app(app)

app.register_blueprint(bp_users, url_prefix='/user')
import views

know_users/auth.py
from flask.ext.login import LoginManager

# In order to avoid circular imports we setup the login extension
# in its own top-level module named auth:
from .users.models import User

login_manager = LoginManager()

login_manager.login_view = "users.login"

@login_manager.user_loader
def load_user(user_id):
    """
    We need to provide a user_loader callback.
    This callback is used to reload the user object from the user ID
    stored in the session.

    It should take the unicode ID of a user, and
    return the corresponding user object. For example:
    """
    return User.get(user_id)

know_users/users/views.py
from flask import Blueprint, redirect, flash, render_template, request, url_for, current_app
from flask.ext.login import login_user, login_required, logout_user
from know_users.users.forms import RegistrationForm, LoginForm
from know_users.users.models import User, all_users

bp = Blueprint('users', __name__,
                  template_folder='templates',
                  static_folder='static')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # login and validate the user...
        login_user(form.user)
        flash("Logged in successfully.")
        return redirect(url_for('index'))
    return render_template("login.html", form=form)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    current_app.logger.info("Form loaded: %r", form)
    if form.validate_on_submit():
        current_app.logger.info("Form validated for %r", form)
        user = User(form.username.data, form.email.data,
                    form.password.data)
        User.add(user)
        flash('Thanks for registering')
        return redirect(url_for('.users_list'))
    return render_template('register.html', form=form)

@bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect('/')


@bp.route("/settings")
@login_required
def settings():
    return render_template('settings.html')

@bp.route("/list")
#@login_required
def users_list():
    current_app.logger.info('%d users registered', len(all_users))
    return render_template('users_list.html', all_users=all_users)

know_users/views.py
from know_users import app
from flask import render_template

@app.route('/')
def index():
    return render_template('index.html')

know_users/templates/flash-msg.html
{% with messages = get_flashed_messages() %}
{% if messages %}
<section class="flashes">
	{% for message in messages %}
	<p>{{ message }}</p>
	{% endfor %}
</section>
{% endif %}
{% endwith %}

know_users/templates/helpers/forms.html
{# ref: http://flask.pocoo.org/docs/patterns/wtforms/?highlight=forms#forms-in-templates #}
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

know_users/templates/index.html
{% extends "layout.html" %}
{% block title %} {{ super() }}- Home{% endblock %}
{% block content %}
{% if current_user.is_authenticated() %}
          <p class="list_caption">
      You have now access to:
      </p>
        <ul>
        <li><a href="{{ url_for('users.users_list') }}">Users List</a></li>
        </ul>
      {% endif %}
{% endblock content %}

know_users/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="utf-8">
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"/>
    {% endblock %}
    <title>{% block title %}{{ constants.APP_NAME }} {% endblock %}</title>
    {% endblock head %}
</head>
  <body>
<header>
    {% block header %}
{% endblock header %}
</header>
 {% include 'flash-msg.html' %}
  {% block body %}
  <h1>{{ self.title() }}</h1>
      {% include 'session-info.html'  %}
  {% block content %}
  {% endblock content %}
      <footer>
            {% block footer %}
{% endblock footer %}
      </footer>
  {% endblock body %}
  </body>
</html>

know_users/templates/session-info.html
 {% block session %}
      <div id="session-info">
	{% if current_user.is_anonymous() %}
      <p class="connect">You are not identified. Please <a href="{{ url_for('users.login') }}">login</a>
          or <a href="{{url_for('users.register')}}">sign in</a> .
      {% else %}
      <p class="connected">You are connected as <em>{{ current_user.id}}</em>.
     When done please <a href="{{ url_for('users.logout') }}">logout</a>.</p>
      </p>
      {% endif %}
      </div>
  {% endblock %}